$axure.loadCurrentPage({
  "url":"vincular_usuarios.html",
  "generationDate":new Date(1464897406400.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"59569775fbe648049a71a1f6764affb5",
    "type":"Axure:Page",
    "name":"Vincular Usuários",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e56a1b57c48b4a0aab6ea592fa68317d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":40,
              "y":244},
            "size":{
              "width":252,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75826140fbd446a2bd479777eea57672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":244},
                "size":{
                  "width":252,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a388e904742c4636acbb33aaf77f948d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":12,
              "y":145},
            "size":{
              "width":143,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"147e24c48be141ed9531da4e67b8e32d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":145},
                "size":{
                  "width":143,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vincular_usuarios/u2.png"}},
{
          "id":"685a44b9841646389777ba229f0c6d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":43,
              "y":193},
            "size":{
              "width":326,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75221b1ff9d42d885e8a3737172f28d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":43,
                  "y":193},
                "size":{
                  "width":326,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f3f03b12a124a92b975d1cd269681f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":43,
              "y":219},
            "size":{
              "width":296,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a765373e5e8b4d2b8424218548eb7a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":43,
                  "y":219},
                "size":{
                  "width":296,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e304282106604f94a84159cd7e6e9984",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":447,
              "y":219},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d441d0e5f3b4ff89bb5bd4d5e1711f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":447,
                  "y":219},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f182d91df4ca4ab7a12434b39b8d5900",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":300},
            "size":{
              "width":141,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46ae01cdf75426c960efa33ae104b79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":300},
                "size":{
                  "width":141,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vincular_usuarios/u10.png"}},
{
          "id":"be2c597c7a9f48a683e6340d1d733a59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":448,
              "y":193},
            "size":{
              "width":319,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798329ea2ea247e38e19aca6d19e9a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":448,
                  "y":193},
                "size":{
                  "width":319,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7305d5832a734e4ab1fc35e8a82ad1d5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":320},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c67684114a1241219b206bbf4fb07de8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":320},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4319903f1a854c7ba2ef41ac1c563996",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":53,
              "y":290},
            "size":{
              "width":62,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71d3f603e06b483bb1badbd611f8f77f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":53,
                  "y":290},
                "size":{
                  "width":62,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vincular_usuarios/u16.png"}},
{
          "id":"0ca277e5d376482ea31f21e642118c28",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":533,
              "y":216},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a9977e7cc9d84ffa9f3a26aaf4967d8f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":976,
              "y":462},
            "size":{
              "width":95,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"29ffd15d72394df186506c06be868a79",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":874,
              "y":462},
            "size":{
              "width":92,
              "height":28}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2114106fe39d41e19d306433171d4e3e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":426},
            "size":{
              "width":1068,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vincular_usuarios/u21_line.png"}},
{
          "id":"2dfd4672fc284205a6066ea8a269818a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "location":{
              "x":14,
              "y":443},
            "size":{
              "width":595,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c112a658a2f47dda4b4d90ba910c219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "location":{
                  "x":14,
                  "y":443},
                "size":{
                  "width":595,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"824753d75ea24e4b88b8569049f0d201",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":50},
            "size":{
              "width":1070,
              "height":80},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1163e92ed124204a08a36c6828e95b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":50},
                "size":{
                  "width":1070,
                  "height":80},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alterar_permissoes_de_acesso/u28.jpg"}},
{
          "id":"65656868ebca4ae786422d809298cc5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana Negrito', 'Verdana'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":19,
              "y":69},
            "size":{
              "width":260,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8ca07e319b6432dad5cfe74636dd108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Negrito', 'Verdana'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":19,
                  "y":69},
                "size":{
                  "width":260,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bee36add9fb24893ba816a9af5ee5e50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":19,
              "y":103},
            "size":{
              "width":697,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1dc84406f8a4bdd806bacd4886b725e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":103},
                "size":{
                  "width":697,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"212c6f3896844f73a2d9be6da209ff71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":127},
            "size":{
              "width":1070,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF336699}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/alterar_permissoes_de_acesso/u34_line.png"}},
{
          "id":"5b42366b6bc54a9f94726b41e2298ea2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"43a8b7b7c35e48059d97d9b8293373e5"}]}},
  "masters":{
    "43a8b7b7c35e48059d97d9b8293373e5":{
      "packageId":"43a8b7b7c35e48059d97d9b8293373e5",
      "type":"Axure:Master",
      "name":"Cabeçalho",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ebda998ad70c49f3b6035a83607f99d9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFCFDFF},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":990,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFEDEDED}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e40b7ad3976a4bc1bc67d52cdc55a7fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFCFDFF},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":990,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFEDEDED}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u12.png"}},
{
            "id":"de898c373b2d4add81b0abefa067088a",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":836,
                "y":60},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"38dac5a935264a78bf77e9b493da4e41",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"899565c6ea7d4d208f1ce0d200d0712c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "size":{
                        "width":102,
                        "height":30},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFD0D8DA}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"924468e045bb4d3584503fde9908747c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "size":{
                            "width":102,
                            "height":30},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFD0D8DA}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/login/u16.png"}}]},
{
                "id":"45e1cc4572a041f79d89ae8b137f919a",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":30},
                  "size":{
                    "width":101,
                    "height":27},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"0047742b63c94071912b020a9f6f00c9",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":101,
                        "height":27}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4fce0a21f0bf4df7978a4348c34a6daa",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "size":{
                            "width":101,
                            "height":27},
                          "limbo":false,
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFD0D8DA}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"4bd835f1b0684b7ba2161829909f6477",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFF6F6F6},
                              "size":{
                                "width":101,
                                "height":27},
                              "limbo":false,
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFD0D8DA}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/login/u20.png"}}]}],
                "parentCellId":"899565c6ea7d4d208f1ce0d200d0712c"}]},
{
            "id":"e04702287389481cb6e8cedb2d9250f0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":844,
                "y":66},
              "size":{
                "width":14,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f893a8fdf33541a48c4f2185ebac9163",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":844,
                    "y":66},
                  "size":{
                    "width":14,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u22.png"}},
{
            "id":"10ac724e8a0c4320aa92986b5bf1ab3f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":914,
                "y":70},
              "size":{
                "width":13,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9dce568068594ce18ffc45566c2b94d5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":914,
                    "y":70},
                  "size":{
                    "width":13,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u24.png"}},
{
            "id":"26e46b0c16f64572922d69a4772c496d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":990,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6cb47e63ba8447eda438173b57d74942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":990,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u26.png"}},
{
            "id":"ef10f0c42a144efba72390001591f841",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"13px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":16,
                "y":15},
              "size":{
                "width":362,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"363e7dd30122481793b7de484b9e7ff1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"13px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":15},
                  "size":{
                    "width":362,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "e56a1b57c48b4a0aab6ea592fa68317d":{
      "scriptId":"u0"},
    "75826140fbd446a2bd479777eea57672":{
      "scriptId":"u1"},
    "a388e904742c4636acbb33aaf77f948d":{
      "scriptId":"u2"},
    "147e24c48be141ed9531da4e67b8e32d":{
      "scriptId":"u3"},
    "685a44b9841646389777ba229f0c6d21":{
      "scriptId":"u4"},
    "a75221b1ff9d42d885e8a3737172f28d":{
      "scriptId":"u5"},
    "8f3f03b12a124a92b975d1cd269681f8":{
      "scriptId":"u6"},
    "a765373e5e8b4d2b8424218548eb7a23":{
      "scriptId":"u7"},
    "e304282106604f94a84159cd7e6e9984":{
      "scriptId":"u8"},
    "3d441d0e5f3b4ff89bb5bd4d5e1711f6":{
      "scriptId":"u9"},
    "f182d91df4ca4ab7a12434b39b8d5900":{
      "scriptId":"u10"},
    "b46ae01cdf75426c960efa33ae104b79":{
      "scriptId":"u11"},
    "be2c597c7a9f48a683e6340d1d733a59":{
      "scriptId":"u12"},
    "798329ea2ea247e38e19aca6d19e9a78":{
      "scriptId":"u13"},
    "7305d5832a734e4ab1fc35e8a82ad1d5":{
      "scriptId":"u14"},
    "c67684114a1241219b206bbf4fb07de8":{
      "scriptId":"u15"},
    "4319903f1a854c7ba2ef41ac1c563996":{
      "scriptId":"u16"},
    "71d3f603e06b483bb1badbd611f8f77f":{
      "scriptId":"u17"},
    "0ca277e5d376482ea31f21e642118c28":{
      "scriptId":"u18"},
    "a9977e7cc9d84ffa9f3a26aaf4967d8f":{
      "scriptId":"u19"},
    "29ffd15d72394df186506c06be868a79":{
      "scriptId":"u20"},
    "2114106fe39d41e19d306433171d4e3e":{
      "scriptId":"u21"},
    "2dfd4672fc284205a6066ea8a269818a":{
      "scriptId":"u22"},
    "5c112a658a2f47dda4b4d90ba910c219":{
      "scriptId":"u23"},
    "824753d75ea24e4b88b8569049f0d201":{
      "scriptId":"u24"},
    "a1163e92ed124204a08a36c6828e95b0":{
      "scriptId":"u25"},
    "65656868ebca4ae786422d809298cc5f":{
      "scriptId":"u26"},
    "b8ca07e319b6432dad5cfe74636dd108":{
      "scriptId":"u27"},
    "bee36add9fb24893ba816a9af5ee5e50":{
      "scriptId":"u28"},
    "d1dc84406f8a4bdd806bacd4886b725e":{
      "scriptId":"u29"},
    "212c6f3896844f73a2d9be6da209ff71":{
      "scriptId":"u30"},
    "5b42366b6bc54a9f94726b41e2298ea2":{
      "scriptId":"u31",
      "ebda998ad70c49f3b6035a83607f99d9":{
        "scriptId":"u32"},
      "e40b7ad3976a4bc1bc67d52cdc55a7fd":{
        "scriptId":"u33"},
      "de898c373b2d4add81b0abefa067088a":{
        "scriptId":"u34"},
      "38dac5a935264a78bf77e9b493da4e41":{
        "scriptId":"u35"},
      "899565c6ea7d4d208f1ce0d200d0712c":{
        "scriptId":"u36"},
      "924468e045bb4d3584503fde9908747c":{
        "scriptId":"u37"},
      "45e1cc4572a041f79d89ae8b137f919a":{
        "scriptId":"u38"},
      "0047742b63c94071912b020a9f6f00c9":{
        "scriptId":"u39"},
      "4fce0a21f0bf4df7978a4348c34a6daa":{
        "scriptId":"u40"},
      "4bd835f1b0684b7ba2161829909f6477":{
        "scriptId":"u41"},
      "e04702287389481cb6e8cedb2d9250f0":{
        "scriptId":"u42"},
      "f893a8fdf33541a48c4f2185ebac9163":{
        "scriptId":"u43"},
      "10ac724e8a0c4320aa92986b5bf1ab3f":{
        "scriptId":"u44"},
      "9dce568068594ce18ffc45566c2b94d5":{
        "scriptId":"u45"},
      "26e46b0c16f64572922d69a4772c496d":{
        "scriptId":"u46"},
      "6cb47e63ba8447eda438173b57d74942":{
        "scriptId":"u47"},
      "ef10f0c42a144efba72390001591f841":{
        "scriptId":"u48"},
      "363e7dd30122481793b7de484b9e7ff1":{
        "scriptId":"u49"}}}});