$axure.loadCurrentPage({
  "url":"alterar_permissoes_de_acesso.html",
  "generationDate":new Date(1464897403692.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5b386f3a056a4d63b69859722c9fcd7d",
    "type":"Axure:Page",
    "name":"Alterar Permissões de Acesso",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f07093d8103a48fbac3a4e7ad03e0ce1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":16,
              "y":228},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b66314620f4e4ef0a620348b678447ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":228},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78f8d65439714633b9c56cee303c19f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":87,
              "y":193},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736256ad3fb040b288bcbe64881673f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":193},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5d59cdf71774c62ab19df694df71032",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":189},
            "size":{
              "width":169,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"651efae928c5496eb3cb946e5b1dc26c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":224},
            "size":{
              "width":169,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b140d3c1ebbc4c1c9bd2c288ff3cb907",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":285},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"edfb0dff8c1740b9ac7ffc26cd6b8b1c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":262},
            "size":{
              "width":1070,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/alterar_permissoes_de_acesso/u7_line.png"}},
{
          "id":"ec671f6c18a74c4a9e8b8c510577eeb1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":285},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d30a869c58b94565b4adc4ccec0a4bc2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"43a8b7b7c35e48059d97d9b8293373e5"},
{
          "id":"69d3602559594537a6341e33b0072176",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":49},
            "size":{
              "width":1070,
              "height":80},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"903a689c588a449abbb9eeaccc991b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":49},
                "size":{
                  "width":1070,
                  "height":80},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alterar_permissoes_de_acesso/u28.jpg"}},
{
          "id":"5cca6801f8864e6289c24d55829d911c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana Negrito', 'Verdana'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":23,
              "y":68},
            "size":{
              "width":260,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d47cf220ed24327a6335670665c6b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Negrito', 'Verdana'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":23,
                  "y":68},
                "size":{
                  "width":260,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32d3ac06343e47dd9d8d78fe924d384c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":23,
              "y":102},
            "size":{
              "width":697,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1bdfa4626a45159d9e9b0f7ebfd6dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":102},
                "size":{
                  "width":697,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2dae18ebf1b42bd95127be72f8d4ef0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":126},
            "size":{
              "width":1070,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF336699}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/alterar_permissoes_de_acesso/u34_line.png"}}]}},
  "masters":{
    "43a8b7b7c35e48059d97d9b8293373e5":{
      "packageId":"43a8b7b7c35e48059d97d9b8293373e5",
      "type":"Axure:Master",
      "name":"Cabeçalho",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ebda998ad70c49f3b6035a83607f99d9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFCFDFF},
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":990,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFEDEDED}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e40b7ad3976a4bc1bc67d52cdc55a7fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFCFDFF},
                  "location":{
                    "x":0,
                    "y":50},
                  "size":{
                    "width":990,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFEDEDED}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u12.png"}},
{
            "id":"de898c373b2d4add81b0abefa067088a",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":836,
                "y":60},
              "size":{
                "width":102,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"38dac5a935264a78bf77e9b493da4e41",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":102,
                    "height":30}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"899565c6ea7d4d208f1ce0d200d0712c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "size":{
                        "width":102,
                        "height":30},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFD0D8DA}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"924468e045bb4d3584503fde9908747c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "size":{
                            "width":102,
                            "height":30},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFD0D8DA}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/login/u16.png"}}]},
{
                "id":"45e1cc4572a041f79d89ae8b137f919a",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":30},
                  "size":{
                    "width":101,
                    "height":27},
                  "limbo":false},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"0047742b63c94071912b020a9f6f00c9",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":101,
                        "height":27}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4fce0a21f0bf4df7978a4348c34a6daa",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "size":{
                            "width":101,
                            "height":27},
                          "limbo":false,
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFD0D8DA}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"4bd835f1b0684b7ba2161829909f6477",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFF6F6F6},
                              "size":{
                                "width":101,
                                "height":27},
                              "limbo":false,
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFD0D8DA}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/login/u20.png"}}]}],
                "parentCellId":"899565c6ea7d4d208f1ce0d200d0712c"}]},
{
            "id":"e04702287389481cb6e8cedb2d9250f0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":844,
                "y":66},
              "size":{
                "width":14,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f893a8fdf33541a48c4f2185ebac9163",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":844,
                    "y":66},
                  "size":{
                    "width":14,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u22.png"}},
{
            "id":"10ac724e8a0c4320aa92986b5bf1ab3f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":914,
                "y":70},
              "size":{
                "width":13,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9dce568068594ce18ffc45566c2b94d5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":914,
                    "y":70},
                  "size":{
                    "width":13,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u24.png"}},
{
            "id":"26e46b0c16f64572922d69a4772c496d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":990,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6cb47e63ba8447eda438173b57d74942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":990,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u26.png"}},
{
            "id":"ef10f0c42a144efba72390001591f841",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"13px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":16,
                "y":15},
              "size":{
                "width":362,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"363e7dd30122481793b7de484b9e7ff1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"13px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":16,
                    "y":15},
                  "size":{
                    "width":362,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "f07093d8103a48fbac3a4e7ad03e0ce1":{
      "scriptId":"u0"},
    "b66314620f4e4ef0a620348b678447ac":{
      "scriptId":"u1"},
    "78f8d65439714633b9c56cee303c19f9":{
      "scriptId":"u2"},
    "736256ad3fb040b288bcbe64881673f6":{
      "scriptId":"u3"},
    "c5d59cdf71774c62ab19df694df71032":{
      "scriptId":"u4"},
    "651efae928c5496eb3cb946e5b1dc26c":{
      "scriptId":"u5"},
    "b140d3c1ebbc4c1c9bd2c288ff3cb907":{
      "scriptId":"u6"},
    "edfb0dff8c1740b9ac7ffc26cd6b8b1c":{
      "scriptId":"u7"},
    "ec671f6c18a74c4a9e8b8c510577eeb1":{
      "scriptId":"u8"},
    "d30a869c58b94565b4adc4ccec0a4bc2":{
      "scriptId":"u9",
      "ebda998ad70c49f3b6035a83607f99d9":{
        "scriptId":"u10"},
      "e40b7ad3976a4bc1bc67d52cdc55a7fd":{
        "scriptId":"u11"},
      "de898c373b2d4add81b0abefa067088a":{
        "scriptId":"u12"},
      "38dac5a935264a78bf77e9b493da4e41":{
        "scriptId":"u13"},
      "899565c6ea7d4d208f1ce0d200d0712c":{
        "scriptId":"u14"},
      "924468e045bb4d3584503fde9908747c":{
        "scriptId":"u15"},
      "45e1cc4572a041f79d89ae8b137f919a":{
        "scriptId":"u16"},
      "0047742b63c94071912b020a9f6f00c9":{
        "scriptId":"u17"},
      "4fce0a21f0bf4df7978a4348c34a6daa":{
        "scriptId":"u18"},
      "4bd835f1b0684b7ba2161829909f6477":{
        "scriptId":"u19"},
      "e04702287389481cb6e8cedb2d9250f0":{
        "scriptId":"u20"},
      "f893a8fdf33541a48c4f2185ebac9163":{
        "scriptId":"u21"},
      "10ac724e8a0c4320aa92986b5bf1ab3f":{
        "scriptId":"u22"},
      "9dce568068594ce18ffc45566c2b94d5":{
        "scriptId":"u23"},
      "26e46b0c16f64572922d69a4772c496d":{
        "scriptId":"u24"},
      "6cb47e63ba8447eda438173b57d74942":{
        "scriptId":"u25"},
      "ef10f0c42a144efba72390001591f841":{
        "scriptId":"u26"},
      "363e7dd30122481793b7de484b9e7ff1":{
        "scriptId":"u27"}},
    "69d3602559594537a6341e33b0072176":{
      "scriptId":"u28"},
    "903a689c588a449abbb9eeaccc991b94":{
      "scriptId":"u29"},
    "5cca6801f8864e6289c24d55829d911c":{
      "scriptId":"u30"},
    "9d47cf220ed24327a6335670665c6b05":{
      "scriptId":"u31"},
    "32d3ac06343e47dd9d8d78fe924d384c":{
      "scriptId":"u32"},
    "cb1bdfa4626a45159d9e9b0f7ebfd6dd":{
      "scriptId":"u33"},
    "b2dae18ebf1b42bd95127be72f8d4ef0":{
      "scriptId":"u34"}}});